"""Профиль redis-cli — только read-глаголы; CONFIG/CLIENT/… только read-подглаголы.
Граница read-only — ACL-юзер (+@read -@dangerous), пароль в Secret.
"""

ID = "redis"
COMMANDS = ["redis-cli"]
DESC = "redis-cli (read-глаголы, CONFIG только GET)"

_ALLOW = [
    "GET",
    "MGET",
    "STRLEN",
    "GETRANGE",
    "SUBSTR",
    "EXISTS",
    "TYPE",
    "TTL",
    "PTTL",
    "EXPIRETIME",
    "PEXPIRETIME",
    "DUMP",
    "TOUCH",
    "SCAN",
    "RANDOMKEY",
    "DBSIZE",
    "KEYS",
    "HGET",
    "HMGET",
    "HGETALL",
    "HKEYS",
    "HVALS",
    "HLEN",
    "HEXISTS",
    "HSCAN",
    "HSTRLEN",
    "HRANDFIELD",
    "LRANGE",
    "LLEN",
    "LINDEX",
    "LPOS",
    "SMEMBERS",
    "SISMEMBER",
    "SMISMEMBER",
    "SCARD",
    "SSCAN",
    "SRANDMEMBER",
    "SINTERCARD",
    "ZRANGE",
    "ZRANGEBYSCORE",
    "ZRANGEBYLEX",
    "ZREVRANGE",
    "ZREVRANGEBYSCORE",
    "ZREVRANGEBYLEX",
    "ZCARD",
    "ZCOUNT",
    "ZSCORE",
    "ZMSCORE",
    "ZRANK",
    "ZREVRANK",
    "ZSCAN",
    "ZLEXCOUNT",
    "ZRANDMEMBER",
    "XRANGE",
    "XREVRANGE",
    "XLEN",
    "XPENDING",
    "GETBIT",
    "BITCOUNT",
    "BITPOS",
    "GEOPOS",
    "GEODIST",
    "GEOSEARCH",
    "GEOHASH",
    "PFCOUNT",
    "INFO",
    "TIME",
    "LASTSAVE",
    "PING",
    "ECHO",
    "LOLWUT",
    "WAIT",
    "SINTER",
    "SUNION",
    "SDIFF",
]
_SUBREADS = {
    "CONFIG": ["GET"],
    "CLIENT": ["LIST", "INFO", "ID", "GETNAME", "NO-EVICT", "NO-TOUCH"],
    "MEMORY": ["USAGE", "STATS", "DOCTOR", "MALLOC-STATS"],
    "ACL": ["LIST", "GETUSER", "CAT", "WHOAMI", "USERS"],
    "CLUSTER": [
        "INFO",
        "NODES",
        "SLOTS",
        "SHARDS",
        "LINKS",
        "MYID",
        "COUNTKEYSINSLOT",
        "GETKEYSINSLOT",
        "KEYSLOT",
    ],
    "LATENCY": ["HISTORY", "LATEST", "DOCTOR", "GRAPH"],
    "SLOWLOG": ["GET", "LEN"],
    "COMMAND": ["COUNT", "DOCS", "INFO", "GETKEYS", "LIST"],
    "XINFO": ["STREAM", "GROUPS", "CONSUMERS"],
    "OBJECT": ["ENCODING", "REFCOUNT", "IDLETIME", "FREQ", "HELP"],
}
_VALUE_FLAGS = [
    "-h",
    "-p",
    "-a",
    "-n",
    "-u",
    "-t",
    "--user",
    "--pass",
    "--timeout",
    "--cacert",
    "--cert",
    "--key",
]


def check(argv, g):
    return g.verbs(
        argv,
        value_flags=_VALUE_FLAGS,
        deny_flags=["--eval", "-x", "--pipe", "--pipe-mode"],
        allow=_ALLOW,
        subreads=_SUBREADS,
    )
